#!/bin/bash

compilation_flags="$(find-cxx-flags "$1")"
if [ ! $? -eq 0 ]; then
   # when compiling standalone executable
   compilation_flags="-c $1" 
fi

clang -Xclang -ast-dump $compilation_flags ${@:2}
